# Generated by Django 4.1.5 on 2023-01-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
